### ISSUE TITLE
为什么很久没有更新了？Why it is not updated for a long time?

### ISSUE THREAD

**Issue by JohnWong** [NSHipster/nshipster.cn#3]
之前看英文版比较多，中文版看得少。今天发现中文版已经年久失修。出于什么原因呢？如果我能有精力做更新和翻译有没有意义？

I used to visit nshipster.com. I find that nshipster.cn is not updated for a long time. What is the reason? If I update this site and translate the articles, is this meaningful?

**Comment by mattt** [comment]
你好 @JohnWong.

自上周一以来，我再次担任NSHipster的执行编辑。 我们现在每周都会在NSHipster.com上发布新内容。 我希望很快能定期更新中文网站。

有关更多信息，请阅读：https://nshipster.com/return/
